---
project:
  type: default
  execute-dir: project
  preview:
    port: 4200
  # output-dir: _output
  render:
    - "*.qmd"
    - "!forberedelse/"
    - "!jss/"
    - "!timer/"
    - "!ugeseddel/"
    - "!synopsis/"

no-browse: true

title: Klassifikation og geokodning af vindmøller med Sentinel-2 billeder
subtitle: Optimal compute, geokodning og machine learning teknikker

kursus: "261E24 Politisk geo-data-science med R: analyse, modellering og visualisering"

authors:
  - name: Aleksander Bang-Larsen
    affiliation: Aarhus Universitet

format:
  html: default
  pdf:
    fig-pos: "tbh"
    tbl-pos: "tb"
    lof: false
    lot: false
    toc: false
    latex-auto-install: true
    keep-tex: true
    include-in-header:
      - file: tex/pagenumbers.tex
      - file: tex/in-header.tex
    template-partials:
      - "tex/before-body.tex"
      - "tex/_titlepage.tex"
    geometry:
      - top=2cm
      - bottom=4cm
      - left=2cm
      - right=2cm
      - heightrounded
    linestretch: 1.5
    papersize: a4

cap-location: top
number-sections: true

fontsize: 11pt

execute:
  echo: false

lang: da

link-citations: true
colorlinks: false
csl: politica-w-ibid.csl

bibliography:
  - references.bib
  - packages.bib
