---
name: Build and publish container

on:
  # cron job to trigger the build on any push to main
  push:
    branches:
      - 'main'
    paths:
      - 'docker/**'
      - '.github/workflows/auto-build-container.yml'
  # schedule:
  # # cron job to trigger the build daily
  # # at 3am on Friday
  #   - cron:  '0 3 * * 5'

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:docker/"
        platforms: linux/amd64
        push: true
        tags: aleksanderbl/geotarget:latest
